class Entidad
class Personaje
class Animal
class Objeto
class Herramienta
class Recurso
class Bloque
class Monito
class Zombie
class Vaca
class Cerdo
class Gallina
class Espada
class Hacha
class Azada
class Arco
class Madera
class Carne
class Semilla
class Arbol
class Agua
class Tierra
class Pasto
class Lava
class Piedra
class Inventario
class Slot
class Cofre
class Mundo
class SistemaTiempo

Entidad <|-- Personaje
Personaje <|-- Monito
Personaje <|-- Zombie
Entidad <|-- Animal
Animal <|-- Vaca
Animal <|-- Cerdo
Animal <|-- Gallina
Objeto <|-- Herramienta
Herramienta <|-- Espada
Herramienta <|-- Hacha
Herramienta <|-- Azada
Herramienta <|-- Arco
Objeto <|-- Recurso
Recurso <|-- Madera
Recurso <|-- Carne
Recurso <|-- Semilla
Objeto <|-- Bloque
Bloque <|-- Arbol
Bloque <|-- Agua
Bloque <|-- Tierra
Bloque <|-- Pasto
Bloque <|-- Lava
Bloque <|-- Piedra
Monito *-- Inventario
Inventario *-- Slot
Cofre *-- Slot
Slot --> Objeto
Mundo *-- SistemaTiempo
Mundo o-- Entidad
SistemaTiempo --> Zombie
