@startuml

'========================
' CLASES BASE
'========================

class Entidad{
 + corazones : int
 + recibirDanio()
}

class Personaje{
 + atacar()
}

class Objeto

class Herramienta{
 + usar()
}

class Recurso

class Bloque


'========================
' PERSONAJES
'========================

class Monito{
 + corazones = 7
}

class Zombie{
 + corazones = 2
}

class Vaca{
 + corazones = 1
}

class Cerdo{
 + corazones = 1
}

class Gallina{
 + corazones = 1
}


'========================
' HERRAMIENTAS
'========================

class Espada{
 + danio = 1
}

class Hacha{
 + danio = 0.5
}

class Pico
class Pala
class CanaPescar


'========================
' RECURSOS
'========================

class Madera
class Piedra
class Hierro
class Oro
class Tierra

class CarneAnimal
class CarneZombie
class Pez


'========================
' BLOQUES DEL MUNDO
'========================

class Arbol
class Lago


'========================
' INVENTARIO
'========================

class Inventario{
 + slots = 5
}

class Slot{
 + cantidad : int
}

class Cofre


'========================
' MUNDO
'========================

class Mundo

class SistemaTiempo{
 + duracionDia = 20
 + duracionNoche = 20
}


'========================
' SISTEMAS DEL JUEGO
'========================

class SistemaCombate{
 + atacar()
 + calcularDanio()
}

class Ataque{
 + danio : float
}

class Corazon{
 + valor : int
}

class SistemaArrojar{
 + generarArrojar()
}

class ArrojarItem{
 + cantidad : int
}

class SistemaComida{
 + comer()
 + curar()
}

class SistemaPesca{
 + pescar()
}


'========================
' HERENCIA
'========================

Entidad <|-- Personaje

Personaje <|-- Monito
Personaje <|-- Zombie
Personaje <|-- Vaca
Personaje <|-- Cerdo
Personaje <|-- Gallina

Objeto <|-- Herramienta
Objeto <|-- Recurso
Objeto <|-- Bloque

Herramienta <|-- Espada
Herramienta <|-- Hacha
Herramienta <|-- Pico
Herramienta <|-- Pala
Herramienta <|-- CanaPescar

Recurso <|-- Madera
Recurso <|-- Piedra
Recurso <|-- Hierro
Recurso <|-- Oro
Recurso <|-- Tierra
Recurso <|-- CarneAnimal
Recurso <|-- CarneZombie
Recurso <|-- Pez


'========================
' RELACIONES CON MULTIPLICIDAD
'========================

Monito "1" *-- "1" Inventario
Inventario "1" *-- "5" Slot
Cofre "1" *-- "*" Slot

Slot "1" --> "0..64" Objeto

Mundo "1" *-- "1" SistemaTiempo
Mundo "1" o-- "*" Entidad

SistemaTiempo "1" --> "*" Zombie

Personaje "1" *-- "1..7" Corazon

SistemaCombate "1" --> "*" Personaje
Personaje "1" --> "*" Ataque
Herramienta "1" --> "1" Ataque

SistemaArrojar "1" --> "*" Personaje
ArrojarItem "1" --> "1" Recurso

SistemaComida "1" --> "1" Monito
SistemaComida "1" --> "*" Recurso

SistemaPesca "1" --> "1" Lago
SistemaPesca "1" --> "1" CanaPescar
SistemaPesca "1" --> "*" Pez

@enduml